// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GS1US.Tests.RTF.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("UNSPSC Membership App", SourceFile="Features\\Unspsc.feature", SourceLine=0)]
    public partial class UNSPSCMembershipAppFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Unspsc.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UNSPSC Membership App", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void NewCustomerBuysPrefixesFromUNSPSC(string membershipType, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New customer buys prefixes from UNSPSC", null, exampleTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.When("I navigate to UNSPSC membership site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
 testRunner.And("I fill primary contact form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And("I check the same-as-primary-contact checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I click on the next button on contact details page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("I select membership type {0} and click next", membershipType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("I click on the license agreement checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I fill contact information using primary contact", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I click on the PayPal button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I proceed with PayPal payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I confirm the payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I see the UNSPSC Thank You page with no prefix", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Corporate Global", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_CorporateGlobal()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Corporate Global", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Corporate Plus", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_CorporatePlus()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Corporate Plus", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Corporate", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_Corporate()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Corporate", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Corporate Individual", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_CorporateIndividual()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Corporate Individual", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Education/Charity/Religious Organization", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_EducationCharityReligiousOrganization()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Education/Charity/Religious Organization", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Government - National/State", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_Government_NationalState()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Government - National/State", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Government - Local", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_Government_Local()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Government - Local", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Trade/Standards Organization", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_TradeStandardsOrganization()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Trade/Standards Organization", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Student/Educator/Researcher", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_StudentEducatorResearcher()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Student/Educator/Researcher", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New customer buys prefixes from UNSPSC, Solution Resources", SourceLine=17)]
        public virtual void NewCustomerBuysPrefixesFromUNSPSC_SolutionResources()
        {
#line 3
this.NewCustomerBuysPrefixesFromUNSPSC("Solution Resources", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
