/* 
 * Data Hub Umbrella API
 *
 * Data Hub umbrella management API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GS1US.Tests.Common.APIs.DataHub.Umbrella.Client.OpenAPIDateConverter;

namespace GS1US.Tests.Common.APIs.DataHub.Umbrella.Model
{
    /// <summary>
    /// UmbrellaChild
    /// </summary>
    [DataContract]
    public partial class UmbrellaChild :  IEquatable<UmbrellaChild>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UmbrellaChild" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UmbrellaChild() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UmbrellaChild" /> class.
        /// </summary>
        /// <param name="companyName">companyName (required).</param>
        /// <param name="childAccountID">childAccountID (required).</param>
        public UmbrellaChild(string companyName = default(string), string childAccountID = default(string))
        {
            // to ensure "companyName" is required (not null)
            if (companyName == null)
            {
                throw new InvalidDataException("companyName is a required property for UmbrellaChild and cannot be null");
            }
            else
            {
                this.CompanyName = companyName;
            }

            // to ensure "childAccountID" is required (not null)
            if (childAccountID == null)
            {
                throw new InvalidDataException("childAccountID is a required property for UmbrellaChild and cannot be null");
            }
            else
            {
                this.ChildAccountID = childAccountID;
            }

        }
        
        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name="CompanyName", EmitDefaultValue=false)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets ChildAccountID
        /// </summary>
        [DataMember(Name="ChildAccountID", EmitDefaultValue=false)]
        public string ChildAccountID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UmbrellaChild {\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  ChildAccountID: ").Append(ChildAccountID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UmbrellaChild);
        }

        /// <summary>
        /// Returns true if UmbrellaChild instances are equal
        /// </summary>
        /// <param name="input">Instance of UmbrellaChild to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UmbrellaChild input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CompanyName == input.CompanyName ||
                    (this.CompanyName != null &&
                    this.CompanyName.Equals(input.CompanyName))
                ) && 
                (
                    this.ChildAccountID == input.ChildAccountID ||
                    (this.ChildAccountID != null &&
                    this.ChildAccountID.Equals(input.ChildAccountID))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CompanyName != null)
                    hashCode = hashCode * 59 + this.CompanyName.GetHashCode();
                if (this.ChildAccountID != null)
                    hashCode = hashCode * 59 + this.ChildAccountID.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ChildAccountID (string) pattern
            Regex regexChildAccountID = new Regex(@"[0-9]{8}", RegexOptions.CultureInvariant);
            if (false == regexChildAccountID.Match(this.ChildAccountID).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ChildAccountID, must match a pattern of " + regexChildAccountID, new [] { "ChildAccountID" });
            }

            yield break;
        }
    }

}
