/* 
 * Data Hub Umbrella API
 *
 * Data Hub umbrella management API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GS1US.Tests.Common.APIs.DataHub.Umbrella.Client.OpenAPIDateConverter;

namespace GS1US.Tests.Common.APIs.DataHub.Umbrella.Model
{
    /// <summary>
    /// UmbrellaDefinitionRequest
    /// </summary>
    [DataContract]
    public partial class UmbrellaDefinitionRequest :  IEquatable<UmbrellaDefinitionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UmbrellaDefinitionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UmbrellaDefinitionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UmbrellaDefinitionRequest" /> class.
        /// </summary>
        /// <param name="parentAccountID">parentAccountID (required).</param>
        /// <param name="childAccountIDs">childAccountIDs (required).</param>
        public UmbrellaDefinitionRequest(string parentAccountID = default(string), List<string> childAccountIDs = default(List<string>))
        {
            // to ensure "parentAccountID" is required (not null)
            if (parentAccountID == null)
            {
                throw new InvalidDataException("parentAccountID is a required property for UmbrellaDefinitionRequest and cannot be null");
            }
            else
            {
                this.ParentAccountID = parentAccountID;
            }

            // to ensure "childAccountIDs" is required (not null)
            if (childAccountIDs == null)
            {
                throw new InvalidDataException("childAccountIDs is a required property for UmbrellaDefinitionRequest and cannot be null");
            }
            else
            {
                this.ChildAccountIDs = childAccountIDs;
            }

        }
        
        /// <summary>
        /// Gets or Sets ParentAccountID
        /// </summary>
        [DataMember(Name="ParentAccountID", EmitDefaultValue=false)]
        public string ParentAccountID { get; set; }

        /// <summary>
        /// Gets or Sets ChildAccountIDs
        /// </summary>
        [DataMember(Name="ChildAccountIDs", EmitDefaultValue=false)]
        public List<string> ChildAccountIDs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UmbrellaDefinitionRequest {\n");
            sb.Append("  ParentAccountID: ").Append(ParentAccountID).Append("\n");
            sb.Append("  ChildAccountIDs: ").Append(ChildAccountIDs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UmbrellaDefinitionRequest);
        }

        /// <summary>
        /// Returns true if UmbrellaDefinitionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UmbrellaDefinitionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UmbrellaDefinitionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ParentAccountID == input.ParentAccountID ||
                    (this.ParentAccountID != null &&
                    this.ParentAccountID.Equals(input.ParentAccountID))
                ) && 
                (
                    this.ChildAccountIDs == input.ChildAccountIDs ||
                    this.ChildAccountIDs != null &&
                    this.ChildAccountIDs.SequenceEqual(input.ChildAccountIDs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ParentAccountID != null)
                    hashCode = hashCode * 59 + this.ParentAccountID.GetHashCode();
                if (this.ChildAccountIDs != null)
                    hashCode = hashCode * 59 + this.ChildAccountIDs.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ParentAccountID (string) pattern
            Regex regexParentAccountID = new Regex(@"[0-9]{8}", RegexOptions.CultureInvariant);
            if (false == regexParentAccountID.Match(this.ParentAccountID).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ParentAccountID, must match a pattern of " + regexParentAccountID, new [] { "ParentAccountID" });
            }

            yield break;
        }
    }

}
